stages:
  - build

cache:
  paths:
    - node_modules/

build-dev:
  image: docker:20.10.8
  services:
    - docker:20.10.8-dind
  variables:
    API_URL:  https://staging-api.werunthecity.id
  before_script:
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  stage: build
  script:
    - docker build --build-arg API_URL="${API_URL}" -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/dev:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/dev:latest
  only:
    - /^dev_[0-9]+(?:.[0-9]+)+$/
